<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WSAMZN-67RC3JA1" failures="1" tests="1" name="Login Page tests" time="20.113" errors="0" timestamp="2022-10-27T19:14:05 IST">
  <testcase classname="Login.Login" name="logintest" time="13.86">
    <failure type="CustomError.CustomError" message="unable to login">
      <![CDATA[CustomError.CustomError: unable to login
at Login.Login.logintest(Login.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
</testsuite> <!-- Login Page tests -->
