<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login.Login" tests="1" skipped="0" failures="1" errors="0" timestamp="2022-10-27T13:43:48" hostname="WSAMZN-67RC3JA1" time="13.86">
  <properties/>
  <testcase name="logintest" classname="Login.Login" time="13.86">
    <failure message="CustomError.CustomError: unable to login" type="CustomError.CustomError">CustomError.CustomError: unable to login
	at app//Login.Login.logintest(Login.java:39)
	at java.base@17.0.3.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3.1/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base@17.0.3.1/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.testng.TestRunner.privateRun(TestRunner.java:794)
	at app//org.testng.TestRunner.run(TestRunner.java:596)
	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at app//org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at app//org.testng.TestNG.runSuites(TestNG.java:1063)
	at app//org.testng.TestNG.run(TestNG.java:1031)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@17.0.3.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3.1/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[[Test worker] INFO testexec - user logged on
]]></system-err>
</testsuite>
